### ISSUE TITLE
dalao要学jetpack了吗

### ISSUE THREAD

**Issue by Kingtous** [ck76/Android-jetpack-demo#1]

**Comment by ck76** [comment]
> 

明年去日本上研究生了，又得重新找工作，找不到新鲜的就还滚去做安卓😭

**Comment by ck76** [comment]
内心是抗拒的，感觉没啥子意思，不想学，只想摸鱼躺着 : (

**Comment by ck76** [comment]
毕业不想回国卷了，日本本土对程序员又不是太友好，没国内这么大需求，总之是另一种形式的卷，不过比国内压力小点

**Comment by Kingtous** [comment]
国内真的卷哎，出国确实好些，而且换个国家生活很新鲜哈哈哈，要是疫情早点结束有空来找你play.

**Comment by Kingtous** [comment]
我现在也没想好做什么，现在比较拿手的也就是android啥的

**Comment by ck76** [comment]
等疫情过了估计就可以过去旅游了👻👻👻
